export const CATEGORY_FETCH_ONE_SUCCESS = 'categories.CATEGORY_FETCH_ONE_SUCCESS';
export const CATEGORY_FETCH_SUCCESS = 'categories.CATEGORY_FETCH_SUCCESS';
export const CATEGORY_CREATE_SUCCESS = 'categories.CATEGORY_CREATE_SUCCESS';
export const CATEGORY_UPDATE_SUCCESS = 'categories.CATEGORY_UPDATE_SUCCESS';
export const CATEGORY_DELETE_SUCCESS = 'categories.CATEGORY_DELETE_SUCCESS';
